config/routes.rb
Rails.application.routes.draw do
  resources :lessonplans
  resources :portions
  resources :periods do
    collection do 
      get 'make_daily_schedule'
      post 'save_daily_schedule'
    end
  end
  resources :time_tables do
    collection do
      get 'show_daily_schedule'
    end
  end
  resources :invoices do
    collection do
      get "items_data"
      post "invoicing"
      get "student_data"
    end
  end

  resources :packages do
    collection do
      get "items_data"
    end
  end

  resources :items do
    collection do
      get 'add_stock'
      get 'adding_stock'
      get 'get_item'
    end
  end
  
  resources :shopcategories
  resources :transportfeerecords do
    collection do
      get 'fee_data'
    end
  end
  resources :year_plans do
    member do
      get 'show_schedule'
      get 'weekly_schedule'
      get 'show_weekly_schedule'
      post 'update_weekly_schedule'
      delete 'delete_weekly_schedule'

    end
    resources :weeks do
      collection do 
        get 'schedule_weeks', :as => :schedule_weeks
        post 'add_schedule_weeks', :as => :add_schedule_weeks

      end
    end
  end

  resources :fees do
    collection do
      get "fee_data"
      get 'fee_defaulter'
    end
  end
  resources :bus_allotments do
    collection do
      get "stops_data"
      get "transports_data"
    end
  end
  resources :stops

  resources :marks
  resources :marksheets do
    member do
      get "upload"
    end
    collection do
      post "uploading"
      get "classresult"
      get "get_class_result"
    end
  end
  resources :exams
  resources :student_holidays
  resources :transports
  resources :routes
  resources :stops
  resources :vehicles

  resources :weekends do
    collection do
      post 'add_weekends'
    end
  end

  resources :subjects
  resources :grades do
    member do
      get 'all_student'
    end
  end
  resources :batches
  resources :leaves do
    member do
      post 'approve_leave'
    end
  end
  resources :positions
  resources :departments
  resources :categories

  get 'emergencies/new'

  get 'emergencies/index'

  get 'emergencies/show'

  resources :parents do
    collection do
      get "parents_data"
    end
    member do 
      get "edit_parent"
    end
  end
  devise_for :users

  get 'home/index'

  resources :bridges do
    member do
        get 'class_subject'
    end
    collection do
      post 'new'
      post 'assign_teacher'
    
    end
  end
  resources :employees do
    collection do
      get 'mark_attendance_calendar'
      post 'mark_attendance'
      post 'save_attendances'
      get 'monthly_attendance_report'
      get 'get_monthly_attendance_report_result'
    end
  end
  resources :emergencies

  root 'home#index'
  resources :students do
    member do
      post "assignParent"
      get "edit_student"
    end
    collection do
      get "detail"
      get 'mark_attendance_calendar'
      post 'mark_attendance'
      post 'save_attendances'
      get 'monthly_attendance_report'
      get 'get_monthly_attendance_report_result'
    end
  end
  resources :documents do
    member do 
      post "addPreviousInfo"
    end
    collection do
      post "upload"
    end
  end

end

app/models/lessonplan.rb
class Lessonplan < ActiveRecord::Base
	belongs_to :year_plan
	has_many :lessonplan_details
	belongs_to :subject
	belongs_to :grade

end

app/controllers/lessonplans_controller.rb
class LessonplansController < ApplicationController
  before_action :set_lessonplan, only: [:show, :edit, :update, :destroy]

  # GET /lessonplans
  # GET /lessonplans.json
  def index
    @year_plan = YearPlan.find(params[:year_plan])
    if @year_plan.present?
      @lessonplans = @year_plan.lessonplans
    end
  end

  # GET /lessonplans/1
  # GET /lessonplans/1.json
  def show
  end

  # GET /lessonplans/new
  def new
    @year_plan = YearPlan.find(params[:year_plan])
    if @year_plan.present?
      @lessonplan = @year_plan.lessonplans.build
      @subjects = Subject.all
      @grades = Grade.all
    end
  end

  # GET /lessonplans/1/edit
  def edit
  end

  # POST /lessonplans
  # POST /lessonplans.json
  def create
    @year_plan = YearPlan.find(params[:lessonplan][:year_plan_id])

    if @year_plan.present?
      @lessonplan = @year_plan.lessonplans.build(lessonplan_params)

   respond_to do |format|
        if @lessonplan.save

          params[:lessonplan_detail_days].each_with_index do |detail_day,i|
            @lessonplan.lessonplan_details.create!(period: params[:lessonplan_detail_days][i], procedure: params[:lessonplan_detail_details][i])
          end

          format.html { redirect_to @lessonplan, notice: 'Portion was successfully created.' }
          format.json { render :show, status: :created, location: @lessonplan }
        else
          format.html { render :new }
          format.json { render json: @lessonplan.errors, status: :unprocessable_entity }
        end
      end
    end
  end

  # PATCH/PUT /lessonplans/1
  # PATCH/PUT /lessonplans/1.json
  def update
    respond_to do |format|
      if @lessonplan.update(lessonplan_params)
        format.html { redirect_to @lessonplan, notice: 'Lessonplan was successfully updated.' }
        format.json { render :show, status: :ok, location: @lessonplan }
      else
        format.html { render :edit }
        format.json { render json: @lessonplan.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /lessonplans/1
  # DELETE /lessonplans/1.json
  def destroy
    @lessonplan.destroy
    respond_to do |format|
      format.html { redirect_to year_plans_url, notice: 'Lessonplan was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_lessonplan
      @lessonplan = Lessonplan.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def lessonplan_params
      params.require(:lessonplan).permit(:grade_id, :subject_id, :topic, :selection, :startdate, :enddate, :studentengage, :newvocabulary, :objectives,:year_plan_id)
    end
end

app/helpers/lessonplans_helper.rb
module LessonplansHelper
end

app/views/lessonplans/_form.html.erb
<%= form_for(@lessonplan) do |f| %>
  <% if @lessonplan.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@lessonplan.errors.count, "error") %> prohibited this lessonplan from being saved:</h2>

      <ul>
      <% @lessonplan.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="form-group">
    <%= f.number_field :year_plan_id, style: 'display:none' %>
  </div>

  <div class="abc form-holder">
        <div class="row">
          <fieldset class="sss well well-lg">
            <legend class="lll">Lesson Plan Information</legend>
              <div class="column col-xs-12 col-sm-3">
                <div class="form-group">
                    <label for="exampleInputEmail1">Class</label>
                    <%= f.select :grade_id, options_from_collection_for_select(@grades,"id", "name"),{prompt: "Select Class"}, {class: 'form-control', required: true} %>
                </div>
              </div>
              <div class="column col-xs-12 col-sm-3">
                <div class="form-group">
                <label for="exampleInputEmail1">Subject</label>
                  <%= f.select :subject_id, options_from_collection_for_select(@subjects,"id", "name"),{prompt: "Select Subject"}, {class: 'form-control', required: true} %>
                </div>
              </div>
              <div class="column col-xs-12 col-sm-3">
                <div class="form-group">
                <label for="exampleInputEmail1">Topic</label>
                  <%= f.text_field :topic , :style => 'height:34px;width: 100%',  class: 'form-control', autofocus: true %>
                </div>
              </div>
              <div class="column col-xs-12 col-sm-3">
                <div class="form-group">
                <label for="exampleInputEmail1">Selection</label>
                  <%= f.text_field :selection , :style => 'height:34px;width: 100%',  class: 'form-control ', autofocus: true %>
                </div>
              </div>
              <div class="column col-xs-12 col-sm-3">
                <div class="form-group">
                <label for="exampleInputEmail1">Start date</label>
                  <%= f.text_field :startdate , :style => 'height:34px;width: 100%',  class: 'form-control datepicker', autofocus: true %>
                </div>
              </div>
              <div class="column col-xs-12 col-sm-3">
                <div class="form-group">
                <label for="exampleInputEmail1">End date</label>
                  <%= f.text_field :enddate , :style => 'height:34px;width: 100%',  class: 'form-control datepicker ', autofocus: true %>
                </div>
              </div>
              <div class="column col-xs-12 col-sm-6">
                <div class="form-group">
                <label for="exampleInputEmail1">Students will engage in</label>
                  <%= f.text_area :studentengage , :style => 'height:44px;width: 100%',  class: 'form-control ', autofocus: true %>
                </div>
              </div>
              <div class="column col-xs-12 col-sm-12">
                <div class="form-group">
                <label for="exampleInputEmail1">New Vocabulary</label>
                  <%= f.text_field :newvocabulary , :style => 'height:34px;width: 100%',  class: 'form-control ', autofocus: true %>
                </div>
              </div>
              <div class="column col-xs-12 col-sm-12">
                <div class="form-group">
                <label for="exampleInputEmail1">Objectives</label>
                  <%= f.text_area :objectives , placeholder: 'Write Objectives here...',cols: 70, rows: 7 ,class: 'form-control ', autofocus: true ,style: 'width:100%' %>
                </div>
              </div>
          </fieldset>       
        </div>
      </div>

  <div class="lessonplan-detail-div">
    <fieldset class="sss well well-lg">
      <legend class="lll">Lesson plan Details</legend>
      <div class="column col-xs-12 col-sm-12">
        <div class="form-group">
          <span>Day</span>
          <%= text_area_tag "lessonplan_detail_days[]", nil, placeholder: 'Write Periods here...',cols: 70, rows: 1, class: 'form-control', style: 'width:100%' %>
        </div>
        <div class="form-group">
          <span>Procedures Followed</span>
          <%= text_area_tag "lessonplan_detail_details[]", nil, placeholder: 'Write Procedures Details here...',cols: 70, rows: 7, class: 'form-control', style: 'width:100%' %>
        </div>
      </div>
    </fieldset>
  </div>

  <%= link_to "Add Another Lesson Plan Detail","javascript:void(0);", class: "btn btn-default add-lessonplan-detail" %>

  <%= link_to "Remove Lesson Plan Detail","javascript:void(0);", class: "btn btn-danger rem-lessonplan-detail" %>


  <div class="form-group">
    <%= f.submit "Save Lesson Plan Details", class: 'btn btn-success pull-right' %>
  </div>
<% end %>


<script type="text/javascript">
  $(document).ready(function(){
    $(function() {
      $(document).on('click','.add-lessonplan-detail', function (e) {
        e.preventDefault();

        var portion_last = $(".lessonplan-detail-div").last();

        var html = "<div class='lessonplan-detail-div'>"+$(".lessonplan-detail-div").html()+"</div>";

        $(html).insertAfter($(".lessonplan-detail-div"));

      });

      $(document).on('click', '.rem-lessonplan-detail', function (e) {
        e.preventDefault(); 
        if( $(".lessonplan-detail-div").length > 1 ){
          $(".lessonplan-detail-div").last().remove();
        }
      });
    });
  });
</script>


  

 






<style type="text/css">
  .form-holder .col-sm-2 {
    min-height: 84px;
  }
  .form-holder .form-control{
    width: 65%;
  }
  .form-control{
    border-radius: 7px;
    border: black;
  }
</style>

<style type="text/css">
  .container{
      width: 1068px;
  }

  .sss{
    border:1px solid#e5e5e5;   padding: 1%; 
  }

  .ttt{
    border:1px solid green;   padding: 1%; 
  }

  .lll{
    width: auto !important; 
    background-color: white;
    padding-right: 16px;
    padding-left: 15px;
    border: 1px solid;
    border-color: blue;
    border-radius: 21px;
  }

  .zzz{
    width: auto !important; 
    background-color: white;
    padding-right: 16px;
    padding-left: 15px;
    border: 1px solid;
    border-color: green;
    border-radius: 21px;
  }

  .form-holder .col-sm-2 {
    min-height: 84px;
  }
  .form-holder .form-control{
    width: 65%;
  }
  .form-control{
    border-radius: 7px;
    border: black;
  }
</style>

app/views/lessonplans/edit.html.erb
<h1>Editing Lessonplan</h1>

<%= render 'form' %>

<%= link_to 'Show', @lessonplan %> |
<%= link_to 'Back', lessonplans_path %>

app/views/lessonplans/index.html.erb
<%= stylesheet_link_tag "//cdn.datatables.net/plug-ins/1.10.7/integration/bootstrap/3/dataTables.bootstrap.css" %>
<%= javascript_include_tag "https://cdn.datatables.net/1.10.7/js/jquery.dataTables.min.js" %>
<%= javascript_include_tag "//cdn.datatables.net/tabletools/2.2.2/js/dataTables.tableTools.min.js" %>
<%= javascript_include_tag "https://cdn.datatables.net/plug-ins/1.10.7/integration/bootstrap/3/dataTables.bootstrap.js" %>
<script type="text/javascript">
  $(document).ready(function() {

    $('#example').dataTable({
        dom: 'T<"clear">lfrtip',
        tableTools: {
            "sSwfPath": "https://cdn.datatables.net/tabletools/2.2.2/swf/copy_csv_xls_pdf.swf"
        }
    });



  });

</script>

<div class="bg-light lter b-b wrapper-md">
  <h1 class="m-n font-thin h3">Lesson Plan
  <a href="<%= new_lessonplan_path(year_plan: @year_plan) %>" class="btn btn-color pull-right" style="width:200px;">Add a new Lesson Plan</a></h1>
  <br>
</div>
<br>
<table class="table" id="example">
  <thead class= "table-head">
    <tr>
      <th>Class</th>
      <th>Subject</th>
      <th>Topic</th>
      <th>Selection</th>
      <th>Startdate</th>
      <th>Enddate</th>
      <th>Students will engage in</th>
      <th>New Vocabulary</th>
      <th>Objectives</th>
      <th>Actions</th>
    </tr>
  </thead>

  <tbody>
    <% @lessonplans.each do |lessonplan| %>
      <tr>
        <td><%= lessonplan.grade.name %></td>
        <td><%= lessonplan.subject.name %></td>
        <td><%= lessonplan.topic %></td>
        <td><%= lessonplan.selection %></td>
        <td><%= lessonplan.startdate %></td>
        <td><%= lessonplan.enddate %></td>
        <td><%= lessonplan.studentengage %></td>
        <td><%= lessonplan.newvocabulary %></td>
        <td><%= lessonplan.objectives %></td>
        <td><%= link_to '', lessonplan,:class =>  'btn btn-success  glyphicon glyphicon-ok-circle' %>
            <%= link_to '', edit_lessonplan_path(lessonplan),:class => ' btn btn-info  glyphicon glyphicon glyphicon-pencil bcc',style: "width:40px;" %>
            <%= link_to '', lessonplan, method: :delete, data: { confirm: 'Are you sure?' } ,:class =>  'btn btn-danger glyphicon glyphicon glyphicon-trash'%>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

app/views/lessonplans/new.html.erb
<div class="bg-light lter b-b wrapper-md">
  <h1 class="m-n font-thin h3">Lesson Plan &nbsp &nbsp &nbsp School Year: <%= @year_plan.year_name %> </h1>
</div>
<div class="wrapper-md">
	<div class="col-md-12">
		<%= render 'form' %>
	</div>
</div>

<%#= link_to 'Back', portions_path %>

app/views/lessonplans/show.html.erb
<div class="bg-light lter b-b wrapper-md">
  <h1 class="m-n font-thin h3">
   
  
  <div class="abc form-holder">
  <div class="text-center">
      <%= "School Year: #{@lessonplan.year_plan.year_name} " %>
    </div>
  
    <%= link_to(@lessonplan, method: :delete, class: 'btn m-b-xs btn-sm btn-danger btn-addon pull-right', data: { confirm: 'This will delete current whole lesson plan. Are you sure that you want to make a new one?' }) do %>

      <i class="fa fa-plus"></i>
        Remake Lesson Plan
    <% end %>
        <div class="row">
          <fieldset class="sss well well-lg">
            <legend class="lll">Lesson Plan Information</legend>
              <div class="column col-xs-12 col-sm-3">
                <div class="form-group">
                    <label for="exampleInputEmail1">Class</label>
                    <%= @lessonplan.grade.name %>
                </div>
              </div>
              <div class="column col-xs-12 col-sm-3">
                <div class="form-group">
                <label for="exampleInputEmail1">Subject</label>
                  <%= @lessonplan.subject.name %>
                </div>
              </div>
              <div class="column col-xs-12 col-sm-3">
                <div class="form-group">
                <label for="exampleInputEmail1">Topic</label>
                  <%= @lessonplan.topic %>
                </div>
              </div>
              <div class="column col-xs-12 col-sm-3">
                <div class="form-group">
                <label for="exampleInputEmail1">Selection</label>
                  <%= @lessonplan.selection %>
                </div>
              </div>
              <div class="column col-xs-12 col-sm-3">
                <div class="form-group">
                <label for="exampleInputEmail1">Start date</label>
                  <%= @lessonplan.startdate %>
                </div>
              </div>
              <div class="column col-xs-12 col-sm-3">
                <div class="form-group">
                <label for="exampleInputEmail1">End date</label>
                  <%= @lessonplan.enddate %>
                </div>
              </div>
              <div class="column col-xs-12 col-sm-6">
                <div class="form-group">
                <label for="exampleInputEmail1">Students will engage in</label>
                  <%= @lessonplan.studentengage %>
                </div>
              </div>
              <div class="column col-xs-12 col-sm-12">
                <div class="form-group">
                <label for="exampleInputEmail1">New Vocabulary</label>
                  <%= @lessonplan.newvocabulary %>
                </div>
              </div>
              <div class="column col-xs-12 col-sm-12">
                <div class="form-group">
                <label for="exampleInputEmail1">Objectives</label>
                  <%= @lessonplan.objectives %>
                </div>
              </div>
          </fieldset>       
        </div>
      </div>
</div>
</h1>

<div class="wrapper-md">
  <table class="table table-striped">
    <thead>
      <tr>
        <th class="text-center">Day</th>
        <th class="text-center">Procedure</th>
      </tr>
    </thead>
    <tbody class="text-center">
      <% @lessonplan.lessonplan_details.each do |pd| %>
        <tr>
          <td><%= pd.period%></td>
          <td><%= pd.procedure %></td>
        </tr>
      <% end %>
    </tbody>
  </table>
</div>

<%= link_to 'Back', year_plans_path %>