config/routes.rb
Rails.application.routes.draw do
  resources :lessonplans
  resources :portions
  resources :periods do
    collection do 
      get 'make_daily_schedule'
      post 'save_daily_schedule'
    end
  end
  resources :time_tables do
    collection do
      get 'show_daily_schedule'
    end
  end
  resources :invoices do
    collection do
      get "items_data"
      post "invoicing"
      get "student_data"
    end
  end

  resources :packages do
    collection do
      get "items_data"
    end
  end

  resources :items do
    collection do
      get 'add_stock'
      get 'adding_stock'
      get 'get_item'
    end
  end
  
  resources :shopcategories
  resources :transportfeerecords do
    collection do
      get 'fee_data'
    end
  end
  resources :year_plans do
    member do
      get 'show_schedule'
      get 'weekly_schedule'
      get 'show_weekly_schedule'
      post 'update_weekly_schedule'
      delete 'delete_weekly_schedule'

    end
    resources :weeks do
      collection do 
        get 'schedule_weeks', :as => :schedule_weeks
        post 'add_schedule_weeks', :as => :add_schedule_weeks

      end
    end
  end

  resources :fees do
    collection do
      get "fee_data"
      get 'fee_defaulter'
    end
  end
  resources :bus_allotments do
    collection do
      get "stops_data"
      get "transports_data"
    end
  end
  resources :stops

  resources :marks
  resources :marksheets do
    member do
      get "upload"
    end
    collection do
      post "uploading"
      get "classresult"
      get "get_class_result"
    end
  end
  resources :exams
  resources :student_holidays
  resources :transports
  resources :routes
  resources :stops
  resources :vehicles

  resources :weekends do
    collection do
      post 'add_weekends'
    end
  end

  resources :subjects
  resources :grades do
    member do
      get 'all_student'
    end
  end
  resources :batches
  resources :leaves do
    member do
      post 'approve_leave'
    end
  end
  resources :positions
  resources :departments
  resources :categories

  get 'emergencies/new'

  get 'emergencies/index'

  get 'emergencies/show'

  resources :parents do
    collection do
      get "parents_data"
    end
    member do 
      get "edit_parent"
    end
  end
  devise_for :users

  get 'home/index'

  resources :bridges do
    member do
        get 'class_subject'
    end
    collection do
      post 'new'
      post 'assign_teacher'
    
    end
  end
  resources :employees do
    collection do
      get 'mark_attendance_calendar'
      post 'mark_attendance'
      post 'save_attendances'
      get 'monthly_attendance_report'
      get 'get_monthly_attendance_report_result'
    end
  end
  resources :emergencies

  root 'home#index'
  resources :students do
    member do
      post "assignParent"
      get "edit_student"
    end
    collection do
      get "detail"
      get 'mark_attendance_calendar'
      post 'mark_attendance'
      post 'save_attendances'
      get 'monthly_attendance_report'
      get 'get_monthly_attendance_report_result'
    end
  end
  resources :documents do
    member do 
      post "addPreviousInfo"
    end
    collection do
      post "upload"
    end
  end

end

app/models/batch.rb
class Batch < ActiveRecord::Base
	has_many :grades
	has_many :exams
end

app/models/bridge.rb
class Bridge < ActiveRecord::Base
	belongs_to :grade
	belongs_to :subject
	belongs_to :employee
	has_many :marksheets
end

app/models/exam.rb
class Exam < ActiveRecord::Base
	belongs_to :batch
	has_many :marksheets
end

app/models/fee.rb
class Fee < ActiveRecord::Base
	belongs_to :student
end

app/models/grade.rb
class Grade < ActiveRecord::Base
	belongs_to :batch
	has_many :bridges
	has_many :subjects ,through: :bridges
	has_many :students
	has_many :marks
	has_many :marksheets
	has_many :items
	has_many :packages
	has_many :lessonplans

	has_many :grade_subjects


	def full_name
	   "#{name} (#{section})"
	end
end

app/models/invoice.rb
class Invoice < ActiveRecord::Base
	belongs_to :items
	belongs_to :student
	has_many :lines

end

app/models/item.rb
class Item < ActiveRecord::Base
	belongs_to :grade
	belongs_to :shopcategory
	
	has_many :packageitems

end

app/models/leave.rb
class Leave < ActiveRecord::Base

	belongs_to :employee
end

app/models/line.rb
class Line < ActiveRecord::Base
	belongs_to :package
	belongs_to :invoice 
	belongs_to :item
end

app/models/mark.rb
class Mark < ActiveRecord::Base
	belongs_to :grade
	has_many :sessionals
end

app/models/package.rb
class Package < ActiveRecord::Base
	belongs_to :grade

	has_many :packageitems
	has_many :lines

	accepts_nested_attributes_for :packageitems
	
end

app/models/parent.rb
class Parent < ActiveRecord::Base
	has_many :students

	has_many :emergencies

	accepts_nested_attributes_for :emergencies
	
end

app/models/period.rb
class Period < ActiveRecord::Base
	belongs_to :time_table
	belongs_to :subject
end

app/models/portion.rb
class Portion < ActiveRecord::Base
	belongs_to :year_plan

	has_many :portion_details
end

app/models/route.rb
class Route < ActiveRecord::Base
	belongs_to :vehicle
	has_many :stops

	has_many :transports
	has_many :bus_allotment
end

app/models/shopcategory.rb
class Shopcategory < ActiveRecord::Base
	has_many :items
end

app/models/stop.rb
class Stop < ActiveRecord::Base
	belongs_to :route

end

app/models/student.rb
class Student < ActiveRecord::Base

	mount_uploader :image, ImageUploader
	
	belongs_to :parent
	belongs_to :grade
	has_many :documents
	has_many :emergencies

	has_one :bus_allotment

	has_many	:emergencies
	has_many :fees

	has_many :student_attendances
	has_one :bus_allotment
	
	accepts_nested_attributes_for :emergencies

	has_many :marksheets

	has_many :invoices
	

	
end

app/models/subject.rb
class Subject < ActiveRecord::Base
	has_many :bridges
	has_many :grades, through: :bridges

	has_many :grade_subjects
	has_many :portion_details
	has_many :lessonplans
	has_many :lessonplan_details
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable
end

app/models/week.rb
class Week < ActiveRecord::Base
	has_many :grade_subjects
	belongs_to :year_plan

	def start_end_date
		"#{start_date.strftime("%d/%m")} - #{end_date.strftime("%d/%m")}"
	end
end

app/controllers/shopcategories_controller.rb
class ShopcategoriesController < ApplicationController
  before_action :set_shopcategory, only: [:show, :edit, :update, :destroy]

  # GET /shopcategories
  # GET /shopcategories.json
  def index
    @shopcategories = Shopcategory.all
  end

  # GET /shopcategories/1
  # GET /shopcategories/1.json
  def show
  end

  # GET /shopcategories/new
  def new
    @shopcategory = Shopcategory.new
  end

  # GET /shopcategories/1/edit
  def edit
  end

  # POST /shopcategories
  # POST /shopcategories.json
  def create
    @shopcategory = Shopcategory.new(shopcategory_params)

    respond_to do |format|
      if @shopcategory.save
        format.html { redirect_to @shopcategory, notice: 'Shopcategory was successfully created.' }
        format.json { render :show, status: :created, location: @shopcategory }
      else
        format.html { render :new }
        format.json { render json: @shopcategory.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /shopcategories/1
  # PATCH/PUT /shopcategories/1.json
  def update
    respond_to do |format|
      if @shopcategory.update(shopcategory_params)
        format.html { redirect_to @shopcategory, notice: 'Shopcategory was successfully updated.' }
        format.json { render :show, status: :ok, location: @shopcategory }
      else
        format.html { render :edit }
        format.json { render json: @shopcategory.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /shopcategories/1
  # DELETE /shopcategories/1.json
  def destroy
    @shopcategory.destroy
    respond_to do |format|
      format.html { redirect_to shopcategories_url, notice: 'Shopcategory was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_shopcategory
      @shopcategory = Shopcategory.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def shopcategory_params
      params.require(:shopcategory).permit(:name)
    end
end

app/helpers/shopcategories_helper.rb
module ShopcategoriesHelper
end

app/views/shopcategories/_form.html.erb
<style type="text/css">
  .container{
      width: auto;
  }

  .sss{
    border:1px solid#e5e5e5;    
  }

  .lll{
    width: auto !important; 
    background-color: white;
    padding-right: 16px;
    padding-left: 15px;
    border: 1px solid;
    border-color: #729F32;
    border-radius: 21px;
  }
</style>

<%= form_for(@shopcategory) do |f| %>
  <% if @shopcategory.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@shopcategory.errors.count, "error") %> prohibited this shopcategory from being saved:</h2>

      <ul>
      <% @shopcategory.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="container form-holder">
        <div class="row">
        <br>
          <fieldset class="sss well well-lg">
             <legend class="lll">Category</legend>
                  <div class = "row">
                      <div class = "col-md-6">
                            <div class="form-group ">
                                <%= f.label :name %><br>
                                <%= f.text_field :name, :style => 'height:34px;',  class: 'form-control' , required: true, autofocus: true  %>
                            </div>
                        </div>
                  </div>
          </fieldset>
        </div>
    </div>

  <div class="actions">
    <%= f.submit "Create", :class => 'btn btn-block btn-success form-control',:style=>'width:24%;float: right;' %>
  </div>
<% end %>


<style type="text/css">
  .form-holder .col-sm-2 {
    min-height: 84px;
  }
  .form-holder .form-control{
    width: 65%;
  }
  .form-control{
    border-radius: 7px;
    border: black;
  }
</style>

app/views/shopcategories/edit.html.erb
<div class="bg-light lter b-b wrapper-md">
  <h1 class="m-n font-thin h3">Editing Categories</h1>
</div>
<div class="wrapper-md">
	<%= render 'form' %>
</div>
	<%= link_to 'Back', shopcategories_path ,class: "btn btn-color"%>

app/views/shopcategories/index.html.erb
<div class="bg-light lter b-b wrapper-md">
  <h1 class="m-n font-thin h3">Categories
  <a href="<%= new_shopcategory_path %>" class="btn pull-right btn-color" style="width:200px;">Add a new Category</a></h1>
</div>

<table class="table" id="example">
  <thead>
    <tr>
      <th>Name</th>
      <th colspan="3">Actions</th>
    </tr>
  </thead>

  <tbody>
    <% @shopcategories.each do |shopcategory| %>
      <tr>
        <td><%= shopcategory.name %></td>
        <td><%= link_to '', shopcategory,:class =>  'btn btn-success  glyphicon glyphicon-ok-circle' %>
            <%= link_to '', edit_shopcategory_path(shopcategory),:class => ' btn btn-info  glyphicon glyphicon glyphicon-pencil bcc',style: "width:40px;" %>
            <%= link_to '', shopcategory, method: :delete, data: { confirm: 'Are you sure?' } ,:class =>  'btn btn-danger glyphicon glyphicon glyphicon-trash'%>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

app/views/shopcategories/new.html.erb
<div class="bg-light lter b-b wrapper-md">
  <h1 class="m-n font-thin h3">Add Ctegory</h1>
</div>


<%= render 'form' %>

<%= link_to 'Back', shopcategories_path,class: "btn btn-color" %>

app/views/shopcategories/show.html.erb
<div class="bg-light lter b-b wrapper-md">
  <h1 class="m-n font-thin h3">Category  </h1>
</div>

<style type="text/css">
    @media(min-width: 1200px)
.abc {
  width: 1080px;
}
</style>
<div class="abc" style="">

    <div class="container" >
    	<div class="abc" style="">

    <div class="container" >
	
		<br>
        <div class="col-sm-4">
            <table class="table">
                <tbody>
                    
                    <tr>
                        <td class="student-profile-td">
                            Category
                        </td>

                        <td>
                            <%= @shopcategory.name %>
                        </td>
                    </tr>

                   
                </tbody>
            </table>
<%= link_to 'Back', shopcategories_path, class: "btn btn-color" %>

        </div>
        </div>
        </div>
        </div>
        </div>