config/routes.rb
Rails.application.routes.draw do
  resources :lessonplans
  resources :portions
  resources :periods do
    collection do 
      get 'make_daily_schedule'
      post 'save_daily_schedule'
    end
  end
  resources :time_tables do
    collection do
      get 'show_daily_schedule'
    end
  end
  resources :invoices do
    collection do
      get "items_data"
      post "invoicing"
      get "student_data"
    end
  end

  resources :packages do
    collection do
      get "items_data"
    end
  end

  resources :items do
    collection do
      get 'add_stock'
      get 'adding_stock'
      get 'get_item'
    end
  end
  
  resources :shopcategories
  resources :transportfeerecords do
    collection do
      get 'fee_data'
    end
  end
  resources :year_plans do
    member do
      get 'show_schedule'
      get 'weekly_schedule'
      get 'show_weekly_schedule'
      post 'update_weekly_schedule'
      delete 'delete_weekly_schedule'

    end
    resources :weeks do
      collection do 
        get 'schedule_weeks', :as => :schedule_weeks
        post 'add_schedule_weeks', :as => :add_schedule_weeks

      end
    end
  end

  resources :fees do
    collection do
      get "fee_data"
      get 'fee_defaulter'
    end
  end
  resources :bus_allotments do
    collection do
      get "stops_data"
      get "transports_data"
    end
  end
  resources :stops

  resources :marks
  resources :marksheets do
    member do
      get "upload"
    end
    collection do
      post "uploading"
      get "classresult"
      get "get_class_result"
    end
  end
  resources :exams
  resources :student_holidays
  resources :transports
  resources :routes
  resources :stops
  resources :vehicles

  resources :weekends do
    collection do
      post 'add_weekends'
    end
  end

  resources :subjects
  resources :grades do
    member do
      get 'all_student'
    end
  end
  resources :batches
  resources :leaves do
    member do
      post 'approve_leave'
    end
  end
  resources :positions
  resources :departments
  resources :categories

  get 'emergencies/new'

  get 'emergencies/index'

  get 'emergencies/show'

  resources :parents do
    collection do
      get "parents_data"
    end
    member do 
      get "edit_parent"
    end
  end
  devise_for :users

  get 'home/index'

  resources :bridges do
    member do
        get 'class_subject'
    end
    collection do
      post 'new'
      post 'assign_teacher'
    
    end
  end
  resources :employees do
    collection do
      get 'mark_attendance_calendar'
      post 'mark_attendance'
      post 'save_attendances'
      get 'monthly_attendance_report'
      get 'get_monthly_attendance_report_result'
    end
  end
  resources :emergencies

  root 'home#index'
  resources :students do
    member do
      post "assignParent"
      get "edit_student"
    end
    collection do
      get "detail"
      get 'mark_attendance_calendar'
      post 'mark_attendance'
      post 'save_attendances'
      get 'monthly_attendance_report'
      get 'get_monthly_attendance_report_result'
    end
  end
  resources :documents do
    member do 
      post "addPreviousInfo"
    end
    collection do
      post "upload"
    end
  end

end

app/models/bridge.rb
class Bridge < ActiveRecord::Base
	belongs_to :grade
	belongs_to :subject
	belongs_to :employee
	has_many :marksheets
end

app/controllers/bridges_controller.rb
class BridgesController < ApplicationController
  before_action :set_bridge, only: [:show, :edit, :update, :destroy]

  # GET /bridges
  # GET /bridges.json
  def index
    @bridges = Bridge.all
  end

  # GET /bridges/1
  # GET /bridges/1.json
  def show
  end

  # GET /bridges/new
  def new
     @employee=Employee.all.pluck(:full_name,:id)
    @bridge = []
    Subject.all.try(:each) do |s|
      temp = {flag: false, subject_id: s.id, employee_id: @employee, class_id: params[:class_id] }
      @bridge << temp
    end
    # @bridge.each do |b|
    #   puts "-"*80
    #   # puts b["flag"]
    # end
  end

  # GET /bridges/1/edit
  def edit
  end

  # POST /bridges
  # POST /bridges.json
  def create
    @bridge = Bridge.new(bridge_params)

    respond_to do |format|
      if @bridge.save
        format.html { redirect_to @bridge, notice: 'Bridge was successfully created.' }
        format.json { render :show, status: :created, location: @bridge }
      else
        format.html { render :new }
        format.json { render json: @bridge.errors, status: :unprocessable_entity }
      end
    end
  end

  def assign_teacher
    # return render json: params
    data = params[:flags]
    data.each_with_index do |flag , i|
      # x = i.to_s
      # my_loop= flag[i]
      if flag.last["check"].present?
        b = Bridge.new
        b.grade_id = params[:grade_id]
        b.subject_id = Subject.find_by_name(flag.last["subject_id"]).id
        b.employee_id = flag.last["teacher_id"]
        b.save
      end
    end
    redirect_to class_subject_bridge_path(params[:grade_id]), alert: "Subjects added successfully"
  end

  # PATCH/PUT /bridges/1
  # PATCH/PUT /bridges/1.json
  def update
    respond_to do |format|
      if @bridge.update(bridge_params)
        format.html { redirect_to @bridge, notice: 'Bridge was successfully updated.' }
        format.json { render :show, status: :ok, location: @bridge }
      else
        format.html { render :edit }
        format.json { render json: @bridge.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /bridges/1
  # DELETE /bridges/1.json
  def destroy
    @bridge.destroy
    respond_to do |format|
      format.html { redirect_to bridges_url, notice: 'Bridge was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  def class_subject
    @subjects = Grade.find(params[:id]).bridges
    @class = Grade.find(params[:id])
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_bridge
      @bridge = Bridge.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def bridge_params
      params.require(:bridge).permit(:subject_id, :grade_id, :employee_id)
    end
end

app/helpers/bridges_helper.rb
module BridgesHelper
end

app/views/bridges/_form.html.erb
<table class= "table">
  <thead>
    <th>Status</th>
    <th>Subject</th>
    <th>Teacher</th>
  </thead>
  <tbody>
    <%= form_tag(assign_teacher_bridges_path, method: :post) do %>
      <% i = 0%>
      <% @bridge.each do |b| %>
        <tr>
          <td>
            <%#= hidden_field_tag 'flags[]', '0' %>
            <%= check_box_tag "flags[#{i}][check]", b["flag"], true, id: "bridge_#{b["subject_id"]}" %> 
          </td>
          <td>
            <%= text_field_tag "flags[#{i}][subject_id]", Subject.find(b[:subject_id]).name %>
          </td>

          <td>
            <%= select_tag "flags[#{i}][teacher_id]",options_for_select(@employee),{prompt: 'Select Teacher'} %>
          </td>
          <%= hidden_field_tag "grade_id", b[:class_id] %>
        </tr>
      <% i = i+1 %>
      <% end %>
    

        <%= submit_tag "Assign Subject", data: { confirm: "Are you sure?" }, class: 'btn btn-success pull-right' %>
    <% end %>

  </tbody>
</table>

app/views/bridges/class_subject.html.erb
<h2>Grade : <%= @class.name %></h2>
<table class= "table">
  <thead>
    <th>Subject</th>
    <th>Teacher Name</th>
    
  </thead>
  <tbody>
    
      <% @subjects.try(:each) do |b| %>
        <tr>  
        	<td><%= b.subject.name %></td>
        	<td><%= b.employee.full_name %></td>
        </tr>
    <% end %>

  </tbody>
</table>

app/views/bridges/edit.html.erb
<h1>Editing Bridge</h1>

<%= render 'form' %>

<%= link_to 'Show', @bridge %> |
<%= link_to 'Back', bridges_path %>

app/views/bridges/index.html.erb
<p id="notice"><%= notice %></p>


<table class="table">
  <thead class="table-head">
    <tr>
      <th>Subject</th>
      <th>Grade</th>
      <th>Employee</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @bridges.each do |bridge| %>
      <tr>
        <td><%= bridge.subject_id %></td>
        <td><%= bridge.grade_id %></td>
        <td><%= bridge.employee_id %></td>
        <td><%= link_to 'Show', bridge %></td>
        <td><%= link_to 'Edit', edit_bridge_path(bridge) %></td>
        <td><%= link_to 'Delete', bridge, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Bridge', new_bridge_path %>

app/views/bridges/new.html.erb
<div class="bg-light lter b-b wrapper-md">
  <h1 class="m-n font-thin h3">Assign Subjects</h1>
</div>


<%= render 'form' %>

app/views/bridges/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Subject:</strong>
  <%= @bridge.subject_id %>
</p>

<p>
  <strong>Grade:</strong>
  <%= @bridge.grade_id %>
</p>

<p>
  <strong>Employee:</strong>
  <%= @bridge.employee_id %>
</p>

<%= link_to 'Edit', edit_bridge_path(@bridge) %> |
<%= link_to 'Back', bridges_path %>