config/routes.rb
Rails.application.routes.draw do
  resources :lessonplans
  resources :portions
  resources :periods do
    collection do 
      get 'make_daily_schedule'
      post 'save_daily_schedule'
    end
  end
  resources :time_tables do
    collection do
      get 'show_daily_schedule'
    end
  end
  resources :invoices do
    collection do
      get "items_data"
      post "invoicing"
      get "student_data"
    end
  end

  resources :packages do
    collection do
      get "items_data"
    end
  end

  resources :items do
    collection do
      get 'add_stock'
      get 'adding_stock'
      get 'get_item'
    end
  end
  
  resources :shopcategories
  resources :transportfeerecords do
    collection do
      get 'fee_data'
    end
  end
  resources :year_plans do
    member do
      get 'show_schedule'
      get 'weekly_schedule'
      get 'show_weekly_schedule'
      post 'update_weekly_schedule'
      delete 'delete_weekly_schedule'

    end
    resources :weeks do
      collection do 
        get 'schedule_weeks', :as => :schedule_weeks
        post 'add_schedule_weeks', :as => :add_schedule_weeks

      end
    end
  end

  resources :fees do
    collection do
      get "fee_data"
      get 'fee_defaulter'
    end
  end
  resources :bus_allotments do
    collection do
      get "stops_data"
      get "transports_data"
    end
  end
  resources :stops

  resources :marks
  resources :marksheets do
    member do
      get "upload"
    end
    collection do
      post "uploading"
      get "classresult"
      get "get_class_result"
    end
  end
  resources :exams
  resources :student_holidays
  resources :transports
  resources :routes
  resources :stops
  resources :vehicles

  resources :weekends do
    collection do
      post 'add_weekends'
    end
  end

  resources :subjects
  resources :grades do
    member do
      get 'all_student'
    end
  end
  resources :batches
  resources :leaves do
    member do
      post 'approve_leave'
    end
  end
  resources :positions
  resources :departments
  resources :categories

  get 'emergencies/new'

  get 'emergencies/index'

  get 'emergencies/show'

  resources :parents do
    collection do
      get "parents_data"
    end
    member do 
      get "edit_parent"
    end
  end
  devise_for :users

  get 'home/index'

  resources :bridges do
    member do
        get 'class_subject'
    end
    collection do
      post 'new'
      post 'assign_teacher'
    
    end
  end
  resources :employees do
    collection do
      get 'mark_attendance_calendar'
      post 'mark_attendance'
      post 'save_attendances'
      get 'monthly_attendance_report'
      get 'get_monthly_attendance_report_result'
    end
  end
  resources :emergencies

  root 'home#index'
  resources :students do
    member do
      post "assignParent"
      get "edit_student"
    end
    collection do
      get "detail"
      get 'mark_attendance_calendar'
      post 'mark_attendance'
      post 'save_attendances'
      get 'monthly_attendance_report'
      get 'get_monthly_attendance_report_result'
    end
  end
  resources :documents do
    member do 
      post "addPreviousInfo"
    end
    collection do
      post "upload"
    end
  end

end

app/models/weekend.rb
class Weekend < ActiveRecord::Base
end

app/controllers/weekends_controller.rb
class WeekendsController < ApplicationController
  before_action :set_weekend, only: [:show, :edit, :update, :destroy]

  # GET /weekends
  # GET /weekends.json
  def index
    @weekends = Weekend.all
  end

  # GET /weekends/1
  # GET /weekends/1.json
  def show
  end

  # GET /weekends/new
  def new
    @weekend = Weekend.new
  end

  # GET /weekends/1/edit
  def edit
  end

  # POST /weekends
  # POST /weekends.json
  def create
    @weekend = Weekend.new(weekend_params)

    respond_to do |format|
      if @weekend.save
        format.html { redirect_to @weekend, notice: 'Weekend was successfully created.' }
        format.json { render :show, status: :created, location: @weekend }
      else
        format.html { render :new }
        format.json { render json: @weekend.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /weekends/1
  # PATCH/PUT /weekends/1.json
  def update
    respond_to do |format|
      if @weekend.update(weekend_params)
        format.html { redirect_to @weekend, notice: 'Weekend was successfully updated.' }
        format.json { render :show, status: :ok, location: @weekend }
      else
        format.html { render :edit }
        format.json { render json: @weekend.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /weekends/1
  # DELETE /weekends/1.json
  def destroy
    @weekend.destroy
    respond_to do |format|
      format.html { redirect_to weekends_url, notice: 'Weekend was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  def add_weekends
    if params[:weekend].present?
      Date::DAYNAMES.each_with_index do |day,d|
        if params[:weekend].find{ |w| w == day }.present?
          weekend_day = Weekend.find_by_weekend_day(d)
          if !weekend_day.present?
            Weekend.create!(weekend_day: d)
          end
        else
          weekend_day = Weekend.find_by_weekend_day(d)
          if weekend_day.present?
            weekend_day.destroy
          end
        end
      end
    end
    flash[:success] = "Weekend Changed successfully"
    redirect_to mark_attendance_calendar_employees_path
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_weekend
      @weekend = Weekend.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def weekend_params
      params.require(:weekend).permit(:weekend_day)
    end
end

app/helpers/weekends_helper.rb
module WeekendsHelper
end

app/views/weekends/_form.html.erb
<%= form_for(@weekend) do |f| %>
  <% if @weekend.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@weekend.errors.count, "error") %> prohibited this weekend from being saved:</h2>

      <ul>
      <% @weekend.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :weekend_day %><br>
    <%= f.number_field :weekend_day %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/weekends/edit.html.erb
<h1>Editing Weekend</h1>

<%= render 'form' %>

<%= link_to 'Show', @weekend %> |
<%= link_to 'Back', weekends_path %>

app/views/weekends/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Weekends</h1>

<table>
  <thead>
    <tr>
      <th>Weekend day</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @weekends.each do |weekend| %>
      <tr>
        <td><%= weekend.weekend_day %></td>
        <td><%= link_to 'Show', weekend %></td>
        <td><%= link_to 'Edit', edit_weekend_path(weekend) %></td>
        <td><%= link_to 'Destroy', weekend, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Weekend', new_weekend_path %>

app/views/weekends/new.html.erb
<h1>New Weekend</h1>

<%= render 'form' %>

<%= link_to 'Back', weekends_path %>

app/views/weekends/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Weekend day:</strong>
  <%= @weekend.weekend_day %>
</p>

<%= link_to 'Edit', edit_weekend_path(@weekend) %> |
<%= link_to 'Back', weekends_path %>